name: Build Test and Release
on:
  push:
    branches:
      - 'main'

env:
  REGISTRY_PATH: ${{ github.workspace }}/registry

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Start Docker registry
        run: |
          docker run -d -p 5000:5000 -v ${REGISTRY_PATH}:/var/lib/registry --name registry registry:2

      - name: Sleepy Build Docker Image
        run: docker build -t localhost:5000/my_sleepy_cat_image:latest .

      - name: Push Docker Image
        run: docker push localhost:5000/my_sleepy_cat_image:latest

      - name: Stop Docker registry
        run: docker stop registry

      - name: Upload Docker registry data for testing
        uses: actions/upload-artifact@v2
        with:
          name: docker-registry-data
          path: ${{ env.REGISTRY_PATH }}/

  testA:
    name: TestA
    needs: build
    runs-on: ubuntu-latest
    outputs:
      output0: ${{ steps.echostep.outputs.test0 }}
    steps:
      - name: Download Docker registry data from build job
        uses: actions/download-artifact@v2
        with:
          name: docker-registry-data
          path: ${{ env.REGISTRY_PATH }}

      - name: Start Docker registry
        run: |
          docker run -d -p 5000:5000 -v ${REGISTRY_PATH}:/var/lib/registry --name registry registry:2

      - name: Wait 60 seconds
        run: sleep 60

      - id: echostep
        name: Echo TestA-output
        run: |
          echo "::set-output name=test0::$(docker run localhost:5000/my_sleepy_cat_image:latest /Prefix.txt)A"

  testB:
    name: TestB
    needs: build
    runs-on: ubuntu-latest
    outputs:
      output0: ${{ steps.echostep.outputs.test0 }}
    steps:
      - name: Download Docker registry data from build job
        uses: actions/download-artifact@v2
        with:
          name: docker-registry-data
          path: ${{ env.REGISTRY_PATH }}

      - name: Start Docker registry
        run: |
          docker run -d -p 5000:5000 -v ${REGISTRY_PATH}:/var/lib/registry --name registry registry:2

      - name: Wait 60 seconds
        run: sleep 60

      - id: echostep
        name: Echo TestB-output
        run: |
          echo "::set-output name=test0::$(docker run localhost:5000/my_sleepy_cat_image:latest /Prefix.txt)B"

  release:
    name: Release
    needs: [TestA, TestB]
    runs-on: ubuntu-latest
    steps:
      - name: Print Test Outputs
        run: echo ${{needs.TestA.outputs.output}} ${{needs.TestB.outputs.output0}}

